packages:
  - 'apps/*'
  - 'packages/*'

importers:
  .:
    devDependencies:
      turbo: ^1.12.0
  apps/mobile:
    dependencies:
      '@scaffai/core': workspace:*
  packages/core: {}
  packages/ui: {}